# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!
pod ‘Alamofire’, ‘~> 3.3’

target 'VivaLnk HealthCheck' do

end

target 'VivaLnk HealthCheckTests' do

end

target 'VivaLnk HealthCheckUITests' do

end

